version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  app:
    build:
      context: .
    ports:
      - "80:3000"
    volumes:
      - ./app:/app
    environment:
      RAILS_ENV:           development
      MYSQL_USER:          root
      MYSQL_PASSWORD:      password
      MYSQL_HOST:          db
      MYSQL_DATABASE:      app_development
      RAILS_SERVE_STATIC_FILES: "true"
    depends_on:
      - db
